swagger: "2.0"
info:
  description: "This is a Swagger API description for the Advice collection on [https://api.adviceslip.com](https://api.adviceslip.com)"
  version: "1.0.0"
  title: "Swagger Advices"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "nagyniki.hu@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.adviceslip.com"
basePath: "/"
tags:
- name: "advice"
  description: "Collection of advices"
  externalDocs:
    description: "Find out more"
    url: "https://api.adviceslip.com"
schemes:
- "https"
- "http"
paths:
  /advice:
    get:
      tags:
      - "advice"
      summary: "Get a random advice"
      description: ""
      operationId: "getRandomAdvice"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AdviceSlip"
definitions:
  AdviceSlip:
    type: "object"
    properties:
      slip:
        $ref: "#/definitions/Advice"
  Advice:
    type: "object"
    properties:
      slip_id:
        type: "string"
      advice:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"